### ISSUE TITLE
Brunch Menus

### ISSUE THREAD

**Issue by Kairi700** [genkimarshall/bigredapp-android#49]
It seems like on the weekends all of the dining halls have the same brunch menu displayed. I noticed this from the past two weekends, and I think the same menu was displayed for brunch for both weekends. The menu also didn't seem to be served at any of the dining halls? (Can't confirm this though.)

**Comment by ghost** [comment]
Okay this definitely seems like something to be looked into. I'm going to be
holding off a bit on handling issues because Cornell released
https://now.dining.cornell.edu/eateries which seems to more than feature-match
our needs for the moment... Too bad it's not open source though... ;_;
It's easy to sniff the API they're using too: 
https://now.dining.cornell.edu/api/1.0/dining/eateries.json
So we might switch to using that if we decide to keep going with this.

**Comment by TrevorEdwards** [comment]
Switched to a webview directly using now.dining.cornell.edu (at Cornell Dining's request) in https://github.com/TrevorEdwards/bigredapp-android/commit/0c257165ef02dfd49bf0a12718b8a6dbd9246540 , so this is resolved.
