### ISSUE TITLE
Hosting on F-Droid

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#54]
[F-Droid](https://f-droid.org/) is an Android app store solely for FOSS (Free and Open Source Software) projects.

It seems like might be a bit of work to submit it, and unfortunately I don't have Android Studio installed at the moment. However, I was thinking maybe at the next OpenSourceCornell meeting, or maybe at some Dev Jam event, @TrevorEdwards you and I sit down together and see how easy it would be to submit and keep it updated on F-Droid?

If it is too much of a hassle and no one else would want it, I give up, but it might be nice to check out :)

**Comment by TrevorEdwards** [comment]
I'd definitely be willing to talk about potentially putting the Big Red App on this, so I suppose we can talk about it at the next meeting and keep this thread updated after discussing.

**Comment by TrevorEdwards** [comment]
After discussing with Genki, we won't be hosting on F-Droid for now due to probably very low audience, but we will include the apk with every new release so that other s do not have to build manually, and in the future we will consider using tools like Travis CI which may provide benefits in the way of this idea.

**Comment by ghost** [comment]
<3
